apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/gru/IdeaProjects/kube_pg/data"
  storageClassName: local
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local