---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  selector:
    matchLabels:
      app: redmine
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        ports:
        - containerPort: 3000
        env:
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redmine-secret
                key: REDMINE_DB_PASSWORD
          - name: REDMINE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: redmine-secret
                key: REDMINE_DB_DATABASE
          - name: REDMINE_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: redmine-secret
                key: REDMINE_DB_USERNAME
          - name: REDMINE_DB_POSTGRES
            valueFrom:
              secretKeyRef:
                name: redmine-secret
                key: REDMINE_DB_POSTGRES
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: redmine-secret
                key: REDMINE_SECRET_KEY_BASE